FROM quay.io/rkrawitz/clusterbuster-base:latest

USER 0
RUN microdnf --setopt=install_weak_deps=0 install -y \
    fio \
    fio-engine-libaio \
    sysbench \
    uperf && \
    microdnf -y clean all && \
    rm -rf /var/cache/yum
USER 1000
