FROM quay.io/rkrawitz/clusterbuster-base:latest

USER 0

# sysbench doesn't need crb (code ready containers), so we won't run
# crb enable
RUN microdnf --setopt=install_weak_deps=0 --enablerepo=crb install -y \
      epel-release epel-next-release && \
    microdnf --setopt=install_weak_deps=0 install -y \
      fio \
      fio-engine-libaio \
      python3-numpy \
      sysbench \
      uperf && \
    microdnf -y clean all && \
    rm -rf /var/cache/yum
USER 1000
