#!/usr/bin/env python3

# Copyright 2022 Robert Krawitz/Red Hat
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import os
import sys
import json
import argparse
from lib.clusterbuster.reporter.ClusterBusterReporter import ClusterBusterReporter

parser = argparse.ArgumentParser(description='Generate ClusterBuster report')
report_formats = ClusterBusterReporter.list_report_formats()

parser.add_argument('-o', '--format', '--output_format', '--output', default='summary', type=str,
                    choices=report_formats)
parser.add_argument('--list_formats', action='store_true', help='List available report formats')
parser.add_argument("files", metavar='file', type=str, nargs='*', help='Files to process')

args = parser.parse_args()
if args.list_formats:
    print('\n'.join(sorted(report_formats)))
    sys.exit(1)

try:
    ClusterBusterReporter.print_report(args.files, format=args.format)
except KeyboardInterrupt:
    sys.exit(1)
except BrokenPipeError:
    sys.exit(1)
