#!/usr/bin/env python3

# Copyright 2022 Robert Krawitz/Red Hat
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import os
import sys
import json
from subprocess import PIPE, Popen
import argparse

parser = argparse.ArgumentParser(description='Generate ClusterBuster report')

parser.add_argument('-o', '--format', '--output_format', '--output', default='summary', type=str,
                    choices={'summary', 'verbose', 'raw',
                    'json-summary', 'json', 'json-verbose'})
args = parser.parse_args()

jdata = json.load(sys.stdin)
if args.format == 'raw':
    json.dump(jdata, sys.stdout, indent = 4)
else:
    workload = jdata["metadata"]["workload"]
    postprocessor = os.path.join(os.path.dirname(__file__), "lib", "clusterbuster",
                     "postprocess", f'{workload}.postprocess')

    if os.path.isfile(postprocessor):
        if os.access(postprocessor, os.X_OK):
            with Popen([postprocessor, '-o', args.format], stdin=PIPE) as command:
                command.communicate(json.dumps(jdata).encode())
        else:
            print(f'Handler {postprocessor} is not executable!', file=sys.stderr)
            sys.exit(1)
    else:
        print(f'Workload {workload} is unhandled!', file=sys.stderr)
        sys.exit(1)

