#!/bin/bash
# Copyright 2022 Robert Krawitz/Red Hat
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

declare OC=${OC:-${KUBECTL:-}}
OC=${OC:-$(type -p oc)}
OC=${OC:-$(type -p kubectl)}	# kubectl might not work, though...

declare image_tag=latest

while getopts 't:' opt ; do
    case "$opt" in
	t) image_tag=$OPTARG ;;
	*)		     ;;
    esac
done

declare images=("quay.io/rkrawitz/clusterbuster-base:$image_tag" "quay.io/rkrawitz/clusterbuster-workloads:$image_tag")

if [[ -n "$("${OC}" get hyperconverged -A --no-headers 2>/dev/null)" ]] ; then
    images+=("quay.io/rkrawitz/clusterbuster-vm:$image_tag")
fi

if [[ -n "$*" ]] ; then
    images=("$@")
fi

images=("${images[@]/#/podman pull }")
command=$(IFS=';'; echo "${images[*]}")

for n in $("${OC}" get node --no-headers |awk '{print $1}') ; do
    "${OC}" debug --no-stdin=true --no-tty=true node/"$n" -- chroot /host sh -c "$command" &
done
wait
