#!/bin/bash

exec 1>&2

trap exit TERM INT

if (($# < 8)) ; then
    echo "Usage: $0 configdir controller_sync_port expected_agents agent_sync_port worker_sync_port expected_clients client_sync_count config tools..."
    exit 1
fi

ln -s /opt/pbench-agent /var/lib

PATH=/usr/local/bin:$PATH

declare configdir=$1; shift	# Secret containing pbench config and private key
declare controller_sync_port=$1; shift
declare expected_agents=$1; shift
declare agent_sync_port=$1; shift
declare worker_sync_port=$1; shift
declare expected_clients=$1; shift
declare client_sync_count=${1:-2}; shift
declare config=$1; shift

if [[ ! -d "$configdir" || ! -f "$configdir/pbench-agent.cfg" || ! -f "$configdir/id_rsa" ]] ; then
    echo "Can't find configdir $configdir or pbench-agent.cfg or secret key"
    exit 1
fi

(umask 077 && cp "$configdir"/id_rsa /opt/pbench-agent/id_rsa && chown pbench:pbench /opt/pbench-agent/id_rsa)

(umask 0333 && cp "$configdir"/pbench-agent.cfg /opt/pbench-agent/config/pbench-agent.cfg && chown pbench:pbench /opt/pbench-agent/config/pbench-agent.cfg)

. /etc/profile.d/pbench-agent.sh

declare -a agents=()
declare -a remote_ports=()
declare -a local_ports=()
declare -a all_ports=()
declare -a ssh_server_pids=()

readarray -t all_ports <<< $(find-free-ports -n $((expected_agents * 2);
for i in $(seq 0 $((expected_agents - 1))) ; do
    remote_ports+=("${all_ports[$i]")
    local_ports+=("${all_ports[$((i+expected_agents))]}")
done
    
while read -r agent ; do
    agents+=("$agent")
    echo "Agent $agent"
    cat >> "$HOME/.ssh/config" <<EOF
Host $agent
StrictHostKeyChecking no
UserKnownHostsFile /dev/null
Port $port
LogLevel ERROR
EOF
done <<< "$(sync.pl -v "$controller_sync_port" "$expected_agents" "${ports[@]}")"

# Special case agent ports; everything else should use defaults.
for agent in "${agents[@]}" ; do
    pbench-register-tool-set --remote="$agent"
done

pbench-user-benchmark --config="$config" -- sync.pl "$worker_sync_port" "$expected_clients" "$client_sync_count" &
echo "Waiting for re-sync after benchmarks"
wait
echo "Moving results"
pbench-move-results
echo "Final sync"
sync.pl "$controller_sync_port" "$expected_agents"
