#!/bin/bash

exec 1>&2

trap exit TERM INT

declare ssh_port=2022

if (($# < 1)) ; then
    echo "Usage: $0 controller_port"
    exit 1
fi

PATH=/usr/local/bin:$PATH

. /etc/profile.d/pbench-agent.sh

mount -t debugfs none /sys/kernel/debug

declare controller_port=$1; shift
declare controller_host=$(ip route get 1 |awk '{print $(NF-2); exit}')
#if [[ -n $1 ]] ; then
#    ssh_port=$1
#fi

# Make sure ssh authorized keys are set up correctly

cat "$HOME/.ssh/id_rsa.pub" >> "$HOME/.ssh/authorized_keys"
chown root "$HOME/.ssh/authorized_keys"
chgrp root "$HOME/.ssh/authorized_keys"

/usr/sbin/sshd -p "$ssh_port"

#sleep 5
# Set up anything we need to for the agent

# Let the controller know that we're ready to go
declare sync_port
sync_port=$(sync_to.pl "$controller_host" "$controller_port" "$ssh_port")
declare ssh_tunnel_pid

if [[ -n "$sync_port" ]] ; then
    :
fi

# And wait around to be released after pbench-move-results
sync_to.pl "$controller_host" "$controller_port" "$ssh_port"

# Tear down anything we may need to for the agent

sleep infinity
