FROM quay.io/pbench/pbench-agent-all-centos-8

RUN dnf --setopt=install_weak_deps=False install -y \
    bind-utils \
    git \
    gcc \
    jq \
    sudo \
    sysbench \
    telnet \
    traceroute && \
    dnf -y clean all && \
    rm -rf /var/cache/yum
