#!/bin/bash

# Copyright 2020 Robert Krawitz/Red Hat
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

exec 1>&2
export LANG=en_US.UTF-8
export LANGUAGE=en_UT.UTF-8
export LC_ALL=C

set -u

declare dns_server
declare -i run_forever=0
declare keyfile=
declare -a verbose=()
declare alias=
declare configdir= # Secret containing pbench config and public and private key
declare -i log_environment=0
declare -i unique_hostname=0
declare -i waitforever=0
declare sshd_args=
trap exit TERM INT

function usage() {
    if [[ -n "$*" ]] ; then
	echo "Unknown option $*"
    fi
    cat 1>&2 <<EOF
Usage: $0 [options] controller_port [controller_host]
       -a alias       Alias to use.  Defaults to hostname.
       -D configdir   Directory containing pbench configuration and public
                      and private key for communication with pbench server.
                      Any files named [nn]-[name] will be sourced in
                      order of name immediately following pbench-agent.sh.
                      NO DEFAULT.
       -H addr=host   Add <host> with the specified <addr> to /etc/hosts.
       -n dns_server  DNS server used to look up the controller host name,
                      if needed.
       -K keyfile     Public and private key files used to
                      communicate with the controller.
       -d             Run forever (daemon)
       -v             Increase ssh verbosity
       -L             Run sshd with global listener
       -q             Log stderr to /tmp/container.log on the pod
                      rather than to the container log stream if there
                      are problems with container logging.
       -u             Provide unique hostname to controller.
                      Useful for running standalone agents as
                      a daemonset or other replica set.
       -e             Log the environment.
       -w	      Do not exit when run is complete.
EOF
    sleep infinity
    exit 1
}

# Need -u disabled for this pending
# https://github.com/distributed-system-analysis/pbench/pull/1746
set +u
# shellcheck disable=1091
. /etc/profile.d/pbench-agent.sh
set -u

export BENCH_ARMY_KNIFE_ROLE=agent
declare -a etchosts_addons=()
declare -A extra_hosts=()

while getopts ":a:D:deH:hK:Ln:quvw" arg ; do
    case "$arg" in
	a) alias=$OPTARG	        ;;
	D) configdir=$OPTARG	        ;;
	d) run_forever=1	        ;;
	e) log_environment=1	        ;;
	H) etchosts_addons+=("$OPTARG") ;;
	h) usage			;;
	K) keyfile=$OPTARG	        ;;
	L) sshd_args=-R		        ;;
	n) dns_server=$OPTARG	        ;;
	q) exec 2>/tmp/container.log    ;;
	u) unique_hostname=1	        ;;
	v) verbose+=("-v")	        ;;
	w) waitforever=1		;;
	*) usage "$arg"			;;
    esac
done

declare datum
declare host

for datum in "${etchosts_addons[@]}" ; do
    if [[ $datum =~ ^([^=]+)=(.+) ]] ; then
	ipaddr=${BASH_REMATCH[1]}
	host=${BASH_REMATCH[2]}
	extra_hosts[$ipaddr]="${extra_hosts[$ipaddr]:-} $host"
    fi
done

for host in "${!extra_hosts[@]}" ; do
    echo "$host ${extra_hosts[$host]}" >> /etc/hosts
done

shift $((OPTIND - 1))

(( $# == 1 || $# == 2 )) || usage

# shellcheck disable=2155
declare myhostname=$(ip route get 1 |awk '{print $(NF-2); exit}')
declare controller_port=$1
declare controller_host=${2:-$myhostname}
if [[ -z "${BAK_SERVER_CONFIG:-}" || -z "${BAK_SERVER_PRIVATE_KEY:-}" ]] ; then
    [[ -z "$configdir" ]] && usage "-D must be specified."
    [[ -d "$configdir" ]] || usage "-D $configdir does not exist."
    [[ -r "$configdir"/pbench-agent.cfg ]] || usage "Expected configuration file $configdir/pbench-agent.cfg does not exist"
    [[ -r "$configdir"/id_rsa ]] || usage "Expected private key $configdir/pbench-agent.cfg does not exist"
fi
[[ -z "$keyfile" && -r "$configdir/id_rsa" ]] && keyfile="$configdir/id_rsa"
[[ $keyfile == '/'* ]] || keyfile="$configdir/$keyfile"
[[ -r "$keyfile" ]] || usage "Private key file $keyfile does not exist."
[[ -r "${keyfile}.pub" ]] || usage "Public key file ${keyfile}.pub does not exist."

if [[ ! -r "$keyfile" || ! -r "${keyfile}.pub" ]] ; then
    echo "Can't find key files $keyfile or $keyfile.pub" 1>&2
    usage
fi
declare server_config=${BAK_SERVER_CONFIG:-$configdir/pbench-agent.cfg}
(umask 0333 && cp "$server_config" /opt/pbench-agent/config/pbench-agent.cfg && chown pbench:pbench /opt/pbench-agent/config/pbench-agent.cfg)

PATH=/usr/local/bin:$PATH
set +u
for f in "$configdir/"* ; do
    if [[ $f =~ /[0-4][[:digit:]]-[^/]* ]] ; then
	echo "Sourcing $f"
	# shellcheck disable=1090
	. "$f"
    fi
done
set -u

if (( log_environment )) ; then
    echo "Environment:" 1>&2
    env | sort 1>&2
fi

(mount |grep -q debugfs) || sudo mount -t debugfs none /sys/kernel/debug

[[ -z "$(shopt -s nullglob; echo "/etc/ssh/ssh_host"*)" ]] && ssh-keygen -A

# Make sure ssh authorized keys are set up correctly

cat "${keyfile}.pub" >> "$HOME/.ssh/authorized_keys"
chown root "$HOME/.ssh/authorized_keys"
chgrp root "$HOME/.ssh/authorized_keys"
# XXXXXX Careful about this...
rm -f /run/nologin

declare -i sshd_port
declare -i ssh_server_pid

read -r sshd_port ssh_server_pid < <(mini-sshd $sshd_args)

if (( !sshd_port )) ; then
    echo "Can't run mini ssh server!"
    exit 1
fi

function run_pbench_agent_once() {
    echo "Running pbench agent" 1>&2
    ip addr 1>&2
    if [[ -n "${dns_server:-}" && $controller_host =~ ^[[:alnum:]][-[:alnum:]]*[[:alnum:]]\.[[:alnum:]][-[:alnum:]]*[[:alnum:]]$ ]] ; then
	echo "Looking for IP address for $controller_host from $dns_server" 1>&2
	while read -r line ; do
	    echo "$line" 1>&2
	    if [[ $line =~ ^$controller_host(\.svc.cluster.local)?\ has\ address\ (.*)$ ||
		      $line =~ (.*)\ has\ address\ (($controller_host)(\.svc.cluster.local)?)$ ]] ; then
		controller_host=${BASH_REMATCH[2]}
		break
	    fi
	done < <(host "$controller_host.svc.cluster.local" "$dns_server")
    fi

    # Let the controller know that we're ready to go
    # shellcheck disable=2155
    if (( unique_hostname )) ; then
	token=$(printf '%d %s %s %s-%09d.%s' "$sshd_port" "$(perl -e 'print int rand() * 999999999')" "$(hostname)" "$(hostname)" "$(perl -e 'print int rand() * 999999999')" "${alias:-$myhostname}")
    else
	token=$(printf '%d %s %s %s' "$sshd_port" "$(perl -e 'print int rand() * 999999999')" "$(hostname)" "${alias:-$myhostname}")
    fi
    echo "Waiting for contact from controller" 1>&2
    # shellcheck disable=2155
    local sync_data=$(sync_to.pl "$controller_host" "$controller_port" "$token")
    echo "Got sync, data $sync_data" 1>&2
    local ssh_tunnel_pid

    if [[ $sync_data = "PASV "* ]] ; then
	# shellcheck disable=2034
	read -r passive remote_ssh_port tunnel_port login <<< "$sync_data"
	echo "Start ssh tunnel" 1>&2
	echo ssh "${verbose[@]}" -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -i "$keyfile" -n -R "$tunnel_port:localhost:$sshd_port" -p "$remote_ssh_port" "${login:+$login@}$controller_host" sleep infinity 1>&2
	ssh "${verbose[@]}" -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -i "$keyfile" -n -R "$tunnel_port:localhost:$sshd_port" -p "$remote_ssh_port" "${login:+$login@}$controller_host" sleep infinity 1>&2 &
	ssh_tunnel_pid=$!
	# Controller will ping us to make sure we're up so we don't need to
	# sync ourselves.
	# shellcheck disable=2064
	trap "kill -9 $ssh_tunnel_pid; exit" TERM INT EXIT
    fi

    # And wait around to be released after pbench-move-results
    echo "Waiting for release from controller" 1>&2
    sync_to.pl "$controller_host" "$controller_port"
}

while : ; do
    (run_pbench_agent_once) || {
	echo "Run pbench agent failed!"
	set +u
	for f in "$configdir/"* ; do
	    if [[ $f =~ /[5-9][[:digit:]]-[^/]* ]] ; then
		echo "Sourcing $f"
		# shellcheck disable=1090
		. "$f"
	    fi
	done
	set -u
	# So we don't "helpfully" get restarted by the controller and messing up
	# the synchronization
	sleep infinity
    }
    set +u
    for f in "$configdir/"* ; do
	if [[ $f =~ /[5-9][[:digit:]]-[^/]* ]] ; then
	    echo "Sourcing $f"
	    # shellcheck disable=1090
	    . "$f"
	fi
    done
    set -u
    echo "*** Agent run complete" 1>&2
    (( waitforever )) && sleep infinity
    (( run_forever )) || break
done
kill "$ssh_server_pid";
